# Generated by Django 3.0.5 on 2020-07-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='default.jpeg', upload_to='profile_pics'),
        ),
    ]
