# Generated by Django 3.0.5 on 2020-07-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clubs',
        ),
    ]
