# Generated by Django 3.0.5 on 2020-07-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0003_clubs_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='tagline',
            field=models.TextField(default=None, max_length=300),
        ),
    ]
