# Generated by Django 3.0.5 on 2020-07-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0006_auto_20200714_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
