# Generated by Django 3.0.5 on 2020-07-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0007_delete_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='content_picture',
            field=models.ImageField(default='', upload_to='club_images'),
        ),
        migrations.AddField(
            model_name='clubs',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='club_images'),
        ),
        migrations.AddField(
            model_name='clubs',
            name='wall_picture',
            field=models.ImageField(default='', upload_to='club_images'),
        ),
    ]
