# Generated by Django 3.0.5 on 2020-07-25 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0008_auto_20200725_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=150)),
                ('club_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clubs.clubs')),
            ],
        ),
    ]
