# Generated by Django 3.0.5 on 2020-08-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0025_auto_20200806_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='club_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clubs.clubs'),
        ),
    ]
