# Generated by Django 3.0.5 on 2020-08-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcomingclubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('wall_pic', models.ImageField(default='', upload_to='upcoming_clubs_images')),
            ],
        ),
    ]
