# Generated by Django 3.0.5 on 2020-08-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happening', '0002_upcomingclubs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('main_pic', models.ImageField(default='', upload_to='external_events_images')),
                ('time', models.TextField(blank=True, max_length=50)),
                ('link', models.URLField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='happening',
            name='description',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='happening',
            name='link',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='happening',
            name='time',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
